<?php
	$coinsB = array();
	$coinsB[] = array('short' => 'BTC',		'full' => 'Bitcoin', 		'image' => '/img/bitcoin.png', 		'balance' => '', 	'graph' => '1');
	$coinsB[] = array('short' => 'BCH', 	'full' => 'Bitcoin Cash', 	'image' => '/img/bitcoin-cash.png',	'balance' => '', 	'graph' => '1831');
	$coinsB[] = array('short' => 'BTG', 	'full' => 'Bitcoin Gold', 	'image' => '/img/bitcoin-gold.png',	'balance' => '', 	'graph' => '2083');
	$coinsB[] = array('short' => 'LTC', 	'full' => 'Litecoin',	 	'image' => '/img/litecoin.png',		'balance' => '', 	'graph' => '2');	
	$coinsB[] = array('short' => 'ETH', 	'full' => 'Ethereum', 		'image' => '/img/ethereum.png',		'balance' => '', 	'graph' => '1027');
	$coinsB[] = array('short' => 'ZEC', 	'full' => 'Zcash', 			'image' => '/img/zcash.png',		'balance' => '', 	'graph' => '1437');	
	$coinsB[] = array('short' => 'DSH', 	'full' => 'Dash', 			'image' => '/img/dash.png',			'balance' => '',	'graph' => '131');
	$coinsB[] = array('short' => 'PPC', 	'full' => 'Peercoin', 		'image' => '/img/peercoin.png',		'balance' => '',	'graph' => '5');
	$coinsB[] = array('short' => 'NMC', 	'full' => 'Namecoin', 		'image' => '/img/namecoin.png',		'balance' => '',	'graph' => '3');
	$coinsB[] = array('short' => 'NVC', 	'full' => 'Novacoin', 		'image' => '/img/novacoin.png',		'balance' => '',	'graph' => '6');

	$coinsB[] = array('short' => 'CLAM', 	'full' => 'Clams', 			'image' => '/img/clams.png',		'balance' => '',	'graph' => '460');
	$coinsB[] = array('short' => 'PIVX', 	'full' => 'PIVX', 			'image' => '/img/pivx.png',			'balance' => '',	'graph' => '1169');
	$coinsB[] = array('short' => 'DOGE', 	'full' => 'Dogecoin', 		'image' => '/img/dogecoin.png',		'balance' => '',	'graph' => '74');
	$coinsB[] = array('short' => 'VTC', 	'full' => 'Vertcoin', 		'image' => '/img/vertcoin.png',		'balance' => '',	'graph' => '99');
	$coinsB[] = array('short' => 'XZC', 	'full' => 'ZCoin', 			'image' => '/img/zcoin.png',		'balance' => '',	'graph' => '1414');
	$coinsB[] = array('short' => 'UNO', 	'full' => 'Unobtanium', 	'image' => '/img/unobtanium.png',	'balance' => '',	'graph' => '67');
	$coinsB[] = array('short' => 'STRAT', 	'full' => 'Stratis', 		'image' => '/img/stratis.png',		'balance' => '',	'graph' => '1343');
	$coinsB[] = array('short' => 'XVG', 	'full' => 'Verge', 			'image' => '/img/verge.png',		'balance' => '',	'graph' => '693');
	$coinsB[] = array('short' => 'USNBT', 	'full' => 'NuBits', 		'image' => '/img/nubits.png',		'balance' => '',	'graph' => '626');
	$coinsB[] = array('short' => 'NAV', 	'full' => 'Navcoin', 		'image' => '/img/nubits.png',		'balance' => '',	'graph' => '377');

	$coinsB[] = array('short' => 'DCR', 	'full' => 'Decred', 		'image' => '/img/decred.png',		'balance' => '',	'graph' => '1168');
	$coinsB[] = array('short' => 'GNT', 	'full' => 'Golem', 			'image' => '/img/golem.png',		'balance' => '',	'graph' => '1455');
	$coinsB[] = array('short' => 'SALT', 	'full' => 'SALT', 			'image' => '/img/salt.png',			'balance' => '',	'graph' => '1996');
	$coinsB[] = array('short' => 'OMG', 	'full' => 'OmiseGo', 		'image' => '/img/omisego.png',		'balance' => '',	'graph' => '1808');
?>