<?php
	$coins = array();
	$coins[] = array('short' => 'BTC', 'full' => 'Bitcoin', 'image' => '/img/bitcoin.png');
	$coins[] = array('short' => 'BCH', 'full' => 'Bitcoin Cash', 'image' => '/img/bitcoin-cash.png');
	$coins[] = array('short' => 'BTG', 'full' => 'Bitcoin Gold', 'image' => '/img/bitcoin-gold.png');
	$coins[] = array('short' => 'LTC', 'full' => 'Litecoin', 'image' => '/img/litecoin.png');	
	$coins[] = array('short' => 'ETH', 'full' => 'Ethereum', 'image' => '/img/ethereum.png');	
	$coins[] = array('short' => 'ZEC', 'full' => 'Zcash', 'image' => '/img/zcash.png');	
	$coins[] = array('short' => 'DSH', 'full' => 'Dash', 'image' => '/img/dash.png');	
?>