<?php
	$exchanges = array();
	$exchanges[] = array('name' => 'WEX.NZ', 	'short' => 'wex', 		'method' => 'pusher');
	$exchanges[] = array('name' => 'HITBTC', 	'short' => 'hitbtc', 	'method' => 'socket');
	$exchanges[] = array('name' => 'POLONIEX', 	'short' => 'poloniex', 	'method' => 'socket');
	$exchanges[] = array('name' => 'BITFINEX', 	'short' => 'bitfinex', 	'method' => 'socket');
	$exchanges[] = array('name' => 'OKCOIN', 	'short' => 'okcoin', 	'method' => 'socket');
	$exchanges[] = array('name' => 'BITSTAMP', 	'short' => 'bitstamp', 	'method' => 'pusher');
	$exchanges[] = array('name' => 'GDAX', 		'short' => 'gdax', 		'method' => 'socket');
?>